name: Bug Report
description: Report a bug in Elara Core
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please fill out the details below.

  - type: input
    id: version
    attributes:
      label: Elara Core Version
      description: Run `pip show elara-core` to check
      placeholder: "0.9.1"
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      options:
        - Claude Code
        - Cursor
        - Windsurf
        - Cline (VS Code)
        - Other
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows (WSL)
        - Windows (native)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error output / logs
      description: Paste any error messages or stack traces
      render: shell
